server:
  port: '9090'
  servlet:
    context-path: /touslestemp
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/touslestemp?createDatabaseIfNotExist=true'
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <your-client-id>
            clientSecret: <your-client-secret>
          github:
            clientId: d5b203b2846697af4f80
            clientSecret: a40baca8ee68cc01ac5199f8591a641f87974fe2
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: 'true'
#    hibernate:
#      ddl-auto: update
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: ${DATABASE_USERNAME:keycloak}
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/touslestemp}
#    password: ${DATABASE_PASSWORD:password}


  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
      location:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: ${MAIL_HOST:smtp.gmail.com}

    username: ${MAIL_USERNAME:imstudent2210@gmail.com}
    password: ${MAIL_PASSWORD:mcpauyptjfcsjgcq}
    port: '587'

app:
  auth:
    tokenExpirationMsec: '864000000'
    tokenSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  oauth2:
    authorizedRedirectUris: http://localhost:4200/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect
logging:
  level:
    org:
      springframework: INFO