server:
  port: '9090'
  servlet:
    context-path: /touslestemp
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/touslestemp'
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
      location:
  mvc:
    path match:
      matching-strategy: ant_path_matcher



#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#
